[package]
name = "reactionsystems"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22"

[dependencies]
dot = "0.1"
lalrpop-util = { version = "0.22", features = ["lexer", "unicode"] }
