[package]
name = "reactionsystems"
version = "0.1.0"
edition = "2024"

[build-dependencies]
lalrpop = "0.22"

[dependencies]
regex = { version = "1.11", features = ["unicode-bool"] }
lalrpop-util = { version = "0.22", features = ["lexer", "unicode"] }
petgraph = { version = "0.8", features = ["serde-1"] }
# petgraph-graphml = { version = "4" }
serde = { version = "1", features = ["derive", "rc"] }
serde_cbor_2 = { version = "*" }
