[workspace]
resolver = "3"
members = [ "analysis", "assert", "bisimilarity", "execution","grammar", "rsprocess"]
exclude = ["*.system", "*.experiment", "/testing/", "*.serial", "*.dot", "*.trace", "*.svg"]

[profile.dev]
split-debuginfo = "unpacked"
