[package]
name = "assert"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { version = "*" }
rsprocess = { path = "../rsprocess/" }
serde = { version = ">=1"}
petgraph = { version = ">=0.8", features = ["serde-1"] }
petgraph-graphml = { version = "*" }
